Budgety/urls.py
from django.contrib import admin
from django.urls import path, include
from index import views as IDviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
]

index/urls.py
from django.urls import path
from index import views

app_name='index'

urlpatterns=[
    path('', views.index, name='index'),
    path('add-budget/', views.addBudget, name='add-budget'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_, name='logout'),
    path('delete-budget/', views.deleteBudget, name='delete-budget')
]

index/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Customer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='customer')
    inc_val = models.IntegerField()
    out_val = models.IntegerField()

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

class Budget(models.Model):
    CHOICES = (
        ('+', 'INCOME'),
        ('-', 'OUTCOME')
    )
    typ = models.CharField(max_length=5, choices=CHOICES)
    value = models.IntegerField()
    desc = models.TextField()
    time = models.DateTimeField(default=timezone.now)
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.desc} => {self.value}'

index/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core import serializers
from index.models import Budget, Customer

import json

from index.valid import budgetValidator


def index(request):
    user = request.user
    context = {}

    if request.user.is_authenticated:

        try:
            customer = Customer.objects.get(user=user)
            incomes = Budget.objects.filter(typ='+', customer=customer)
            outcomes = Budget.objects.filter(typ='-', customer=customer)
            context = {
                'inc_val': customer.inc_val,
                'out_val': customer.out_val,
                'total_val': customer.inc_val-customer.out_val,
                'incomes': incomes,
                'outcomes': outcomes, }
        except Exception as e:
            print(e)

    return render(request, 'index.html', context)


def addBudget(request):
    user = request.user

    if user.is_authenticated:
        data = json.loads(request.body)
        result = budgetValidator(data)
        new_val = (data['value'])
        desc = data['desc']
        typ = data['type']
        customer = Customer.objects.get(user=request.user)

        if result['error']:
            return JsonResponse(result['resp'], safe=False)
        else:
            newbudget = Budget.objects.create(
                value=int(new_val), desc=desc, typ=typ, customer=customer)

            if (typ == '+'):
                customer.inc_val = customer.inc_val + int(new_val)
            else:
                customer.out_val = customer.out_val + int(new_val)

            newbudget.save()
            customer.save()

            newbudget = serializers.serialize('json', [newbudget])
            return JsonResponse([newbudget], safe=False)
    else:
        resp = {'error': True, 'msg': 'You Have To Be Logged In'}
        return JsonResponse(resp, safe=False)


def deleteBudget(request):
    if request.user.is_authenticated:
        resp={}
        try:

            budg_id = json.loads(request.body)['budg_id']
            customer = Customer.objects.get(user=request.user)
            budget = Budget.objects.get(id=budg_id, customer=customer)
            budget.delete()
            resp['msg'] = 'Successfully Deleted'
            return JsonResponse(resp, safe=False)

        except Exception as e:
            resp['msg'] = 'Something Went Wrong'
            return JsonResponse(resp, safe=False)
    
    resp['msg'] = 'Please Login First'
    return JsonResponse(resp, safe=False)


def signup(request):
    if request.user.is_authenticated:
        auth.logout(request)

    if request.method == 'POST':
        data = json.loads(request.body)

        # CHECK PASSWORD SHOULD BE MATCHED
        if(data['password'] != data['r_password']):
            resp = {'error': True, 'msg': 'Password Does not match'}
            return JsonResponse(resp, safe=False)

        # TO CHECK FOR EMPTY FIELDS
        for key, val in data.items():
            if val == '':
                resp = {'key': key, 'error': True}
                return JsonResponse(resp, safe=False)

        try:
            user = User.objects.create_user(
                first_name=data['full_name'],
                username=data['username'],
                password=data['password'])
            customer = Customer.objects.create(inc_val=0, out_val=0, user=user)
            customer.save()
            user.save()

            auth.login(request, user)

            resp = {'error': False, 'msg': 'Sign Up Successfully'}
            return JsonResponse(resp, safe=False)

        except:
            resp = {'error': True, 'msg': 'Try Again'}
            return JsonResponse(resp, safe=False)

    else:
        return render(request, 'signup.html')


def login(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        user = auth.authenticate(
            request, username=data['username'], password=data['password'])

        if user is not None:
            auth.login(request, user)
            resp = {'error': False, 'msg': 'Logged in'}
            return JsonResponse(resp, safe=False)
        else:
            resp = {'error': True, 'msg': 'Please Try Again!'}
            return JsonResponse(resp, safe=False)
    else:
        return render(request, 'login.html')


def logout_(request):
    auth.logout(request)
    return redirect('/')

index/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Budgety</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <script src="{% static 'js/script.js' %}" defer></script>
  </head>
  <body>
    <header>
      <div class="available-budget">
        <p>TOTAL : $ <span id="total-inc-out">{{total_val}}</span></p>
        <p>INCOME : $ <span id="total-income">{{inc_val}}</span></p>
        <p>OUTCOME : $ <span id="total-outcome">{{out_val}}</span></p>
      </div>
    </header>
    <div class="auth">

        {% if user.is_authenticated %}
        <p>
          <p>Welcome {{ user.get_full_name }}</p>
          <a href="{% url 'index:logout' %}">Logout</a>
        </p>
        {% else %}
        <p>
          <a

            class="btn mt-3 d-inline-block btn-primary"
            href="{% url 'index:login' %}"
            >Login</a
          >
          <a
            class="btn mt-3 d-inline-block btn-primary"
            href="{% url 'index:signup' %}"
            >Signup</a
          >
        </p>
        {% endif %}
    </div>
    <form method="post" class="budget-form">
      <select id="type" class="description-item">
        <option value="+">+</option>
        <option value="-">-</option>
      </select>
      <input
        type="text"
        id="desc"
        value="hfef"
        class="description-item"
        placeholder="Add Income Or Outcome"
      />
      <input
        type="number"
        placeholder="Value"
        id="value"
        value="4242"
        class="description-item"
      />
      <button id="add-btn">Add</button>
    </form>

    <div class="inc-out-list">
      <div id="incomes-list">
        <p>INCOME</p>
        <ul id="income-ul">
            {% if incomes %}

                {% for inc in incomes %}
                    <li>
                        <h1>{{ inc.desc }}</h1>
                        <p>{{ inc.value }}</p>
                        <button class="delete" id="{{inc.id}}">x</button>
                    </li>
                {% endfor %}

          {% endif %}
        </ul>
      </div>
      <div id="outcomes-list">
        <p>OUTCOME</p>
        <ul id="outcome-ul">
            {% if incomes %}

                {% for out in outcomes %}
                    <li>
                        <h1>{{ out.desc }}</h1>
                        <p>{{ out.value }}</p>
                        <button class="delete" id="{{out.id}}">x</button>

                    </li>
                {% endfor %}
            
            {% endif %}

        </ul>
      </div>
    </div>
  </body>
</html>

index/templates/login.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />

<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<script src="{% static 'js/auth.js' %}" defer></script>
{% block content %}
<section class="login py-5 border-top-1">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-5 col-md-8 align-item-center">
        <div class="border">
          <h3 class="bg-gray p-4">
            Login Now
            <p class="error" id="login-error"></p>
          </h3>

          <form method="POST" id="login-form">
            <fieldset class="p-4">
                
              <input
                id="username"
                type="text"
                placeholder="Username"
                class="border p-3 w-100 my-2"
              />
              <input
                id="password"
                type="password"
                placeholder="Password"
                class="border p-3 w-100 my-2"
              />
              <div>
                <button
                  type="submit"
                  id="login-btn"
                  class="btn mt-3 d-inline-block btn-primary"
                  style="width: 100px"
                >
                  Login
                </button>
                <a
                  style="height: 40px"
                  class="btn mt-3 d-inline-block btn-primary"
                  href="{% url 'index:signup' %}"
                  >Register
                </a>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

index/templates/signup.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
<script src="{% static 'js/auth.js' %}" defer></script>
{% block content %}

<section class="login py-5 border-top-1">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-5 col-md-8 align-item-center">
        <div class="border border">
          <h3 class="bg-gray p-4">Register Now</h3>
          <form method="POST" id="signup-form">
            <fieldset class="p-4">
              <input
                id="full_name"
                type="text"
                placeholder="Full Name*"
                class="border p-3 w-100 my-2"
              />

              <input
                id="username"
                type="text"
                placeholder="Username*"
                class="border p-3 w-100 my-2"
              />

              <input
                id="password"
                type="password"
                placeholder="Password*"
                class="border p-3 w-100 my-2"
              />
              <input
                id="r_password"
                type="password"
                placeholder="Confirm Password*"
                class="border p-3 w-100 my-2"
              />

              <button type="submit" class="btn mt-3 d-inline-block btn-primary">
                Register
              </button>
              <a
                style="height: 40px"
                href="{% url 'index:login' %}"
                class="btn mt-3 d-inline-block btn-primary"
                >Login</a
              >
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}